### Get all contacts
GET http://localhost:3000/contacts

### Get contact by ID
GET http://localhost:3000/contacts/688197a2ec3697314883aa48

### Create contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Tumi",
  "lastName": "Meletse",
  "email": "tumi@example.com",
  "favoriteColor": "blue",
  "birthday": "1999-01-01"
}

### Update contact
PUT http://localhost:3000/contacts/688197a2ec3697314883aa48
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "User",
  "email": "updated@example.com",
  "favoriteColor": "green",
  "birthday": "2000-12-31"
}

### Delete contact
DELETE http://localhost:3000/contacts/68819860ec3697314883aa4bE

### Swagger docs
GET http://localhost:3000/api-docs
