### Get all contacts
GET cse-341-project1-0cop.onrender.com/contacts
### Get all tasks
GET cse-341-project1-0cop.onrender.com/tasks

### Get all menu
GET cse-341-project1-0cop.onrender.com/menu

### Get all orders
GET cse-341-project1-0cop.onrender.com/orders

### Get contact by ID
GET cse-341-project1-0cop.onrender.com/contacts/688197a2ec3697314883aa48

### Get taks by ID
GET cse-341-project1-0cop.onrender.com/tasks/68857044648d07b41e2225a7

### Create contact
POST cse-341-project1-0cop.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Tumi",
  "lastName": "Meletse",
  "email": "tumi@example.com",
  "favoriteColor": "blue",
  "birthday": "1999-01-01"
}

### Create task
POST cse-341-project1-0cop.onrender.com/tasks
Content-Type: application/json

{
  "title": "Computer2",
  "description": "operating 2 systems",
  "assignedTo": "test2@test2.com",
  "dueDate": "2025-07-10",
  "priority": "High",
  "status": "In Progress",
  "createdAt": "2025-06-19",
  "updatedAt": "2025-06-18"

}

### Update contact
PUT cse-341-project1-0cop.onrender.com/contacts/688197a2ec3697314883aa48
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "User",
  "email": "updated@example.com",
  "favoriteColor": "green",
  "birthday": "2000-12-31"
}

### Update tasks
PUT cse-341-project1-0cop.onrender.com/tasks/68856cd5648d07b41e2225a5
Content-Type: application/json

{
  "title": "LAPTOP",
  "description": "Windows 11",
  "assignedTo": "test2@test2.com",
  "dueDate": "2025-05-11",
  "priority": "High",
  "status": "In Progress",
  "createdAt": "2025-06-19",
  "updatedAt": "2025-06-18"

}

### Delete contact
DELETE cse-341-project1-0cop.onrender.com/contacts/68856cd5648d07b41e2225a5

### Swagger docs
GET cse-341-project1-0cop.onrender.com/api-docs
